<div id="abonnement-widget" class="container">
    <div class="col-sm-12">
        <div class="row">
            <?php for ($i=1;$i<=4;$i++): ?>
                <?php $produit = $this->getProduct($this, $i); ?>
                <?php if ($produit): ?>
                    <?php $produitAbonnement = $this->getProductAbonnement($produit); ?>
                    <?php if ($i == 1) { $referencePrice = $produitAbonnement->getPrice();} ?>
                    <div class="abonnement-single col-sm-3">
                        <?php $superGroup[$produitAbonnement->getId()] = $produitAbonnement->getQty(); ?>

                        <!-- Name -->
                        <p><?php echo $produitAbonnement->getName(); ?></p>

                        <!-- Month number -->
                        <p><?php echo $i . " " . $this->__('month'); ?></p>

                        <!-- Price -->
                        <?php if ($i == 1): ?>
                            <p><?php echo Mage::helper('core')->currency($produitAbonnement->getPrice(), true, false); ?> / <?php echo $this->__('month'). ' + ' . $this->__('shipping fees'); ?></p><br/>
                        <?php else: ?>
                             <p><?php echo Mage::helper('core')->currency($produitAbonnement->getPrice(), true, false); ?> / <?php echo $this->__('month'). ' (' . $this->__('total ') . Mage::helper('core')->currency($produitAbonnement->getPrice() * $produitAbonnement->getQty(), true, false) . ') + ' . $this->__('shipping fees'); ?></p>
                        <?php endif; ?>
                            
                        <!-- Savings -->
                        <?php if ($i == 1): ?>
                            <p style="visibility: hidden;"><?php echo $this->__('Save') . " " . Mage::helper('core')->currency(($referencePrice * $produitAbonnement->getQty()) - ($produitAbonnement->getPrice() * $produitAbonnement->getQty()), true, false); ?></p>
                        <?php else: ?>
                            <p><?php echo $this->__('Save') . " " . Mage::helper('core')->currency(($referencePrice * $produitAbonnement->getQty()) - ($produitAbonnement->getPrice() * $produitAbonnement->getQty()), true, false); ?></p>
                        <?php endif; ?>

                        <!-- Payment -->
                        <p><?php echo $this->__('One time payment'); ?></p>

                        <!-- Add to Cart -->
                        <button onclick="showOptions('<?php echo $produit->getId(); ?>')"><?php echo $this->__('Add to Cart'); ?></button>
                        <a href="<?php echo Mage::getUrl('ajaxcart/index/options/', array("product_id" => $produit->getId())); ?>" class="fancybox" id="fancybox<?php echo $produit->getId(); ?>" style="display:none">Options</a>
                    </div>
                <?php endif; ?>
            <?php endfor;?>
        </div>
    </div>
</div>